"""SQL validation using sqlglot — ensures generated SQL is safe to execute."""

import logging

import sqlglot
from sqlglot import exp

from .models import VistaPermitida

logger = logging.getLogger(__name__)

BLOCKED_SCHEMAS = {"information_schema", "pg_catalog", "pg_toast"}


def validar_sql(sql: str) -> dict:
    """Validate SQL generated by the LLM before execution.

    Returns:
        {"valido": True, "sql_final": str} or {"valido": False, "error": str}
    """
    try:
        statements = sqlglot.parse(sql, dialect="postgres")
    except sqlglot.errors.ParseError as exc:
        return {"valido": False, "error": f"SQL parse error: {exc}"}

    # Must be exactly one statement
    if len(statements) != 1:
        return {"valido": False, "error": "Only a single SQL statement is allowed."}

    stmt = statements[0]

    # Must be a SELECT
    if not isinstance(stmt, exp.Select):
        return {"valido": False, "error": "Only SELECT statements are allowed."}

    # Check referenced tables against whitelist
    allowed_views = set(
        VistaPermitida.objects.filter(activa=True).values_list("nombre", flat=True)
    )

    for table in stmt.find_all(exp.Table):
        table_name = table.name.lower() if table.name else ""
        schema_name = table.db.lower() if table.db else ""

        if schema_name in BLOCKED_SCHEMAS:
            return {"valido": False, "error": f"Access to schema '{schema_name}' is forbidden."}

        if table_name not in {v.lower() for v in allowed_views}:
            return {"valido": False, "error": f"Table/view '{table_name}' is not in the allowed list."}

    # Inject LIMIT if missing
    sql_final = sql.rstrip().rstrip(";")
    if not stmt.find(exp.Limit):
        sql_final += " LIMIT 500"

    return {"valido": True, "sql_final": sql_final}
