# Generated by Django 5.1.15 on 2026-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, default='', max_length=100)),
                ('tool_used', models.CharField(blank=True, default='', max_length=100)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(default=dict)),
                ('sql_generated', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('low_confidence', 'Low Confidence'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='ok', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('endpoint', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key', 'endpoint'), name='unique_idempotency_per_endpoint')],
            },
        ),
    ]
