# Generated by Django 5.1.15 on 2026-07-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('vista', models.CharField(max_length=100)),
                ('filtro_fijo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('sinonimos', models.JSONField(blank=True, default=list)),
                ('medida_columna', models.CharField(max_length=50)),
                ('medida_alias', models.CharField(default='tariff_value', max_length=50)),
                ('unidad_columna', models.CharField(blank=True, max_length=50)),
                ('moneda_columna', models.CharField(blank=True, max_length=50)),
                ('orden_por', models.CharField(default='valid_from', max_length=50)),
                ('orden_desc', models.BooleanField(default=True)),
                ('expone_tool_determinista', models.BooleanField(default=True)),
                ('permite_flexible', models.BooleanField(default=True)),
                ('handler', models.CharField(blank=True, help_text='Nombre de función registrada en handlers.py; vacío = lookup genérico', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
            },
        ),
        migrations.CreateModel(
            name='VistaPermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vista Permitida',
                'verbose_name_plural': 'Vistas Permitidas',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('columna', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('texto', 'texto'), ('periodo', 'periodo'), ('numero', 'numero')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('comparador', models.CharField(choices=[('=', '='), ('ILIKE', 'ILIKE')], default='=', max_length=10)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='sqlsafe.metrica')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'unique_together': {('metrica', 'nombre')},
            },
        ),
    ]
