# Generated by Django 5.1.15 on 2026-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('conversation_id', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation Memory',
                'verbose_name_plural': 'Conversation Memories',
                'unique_together': {('user_id', 'conversation_id', 'key')},
            },
        ),
    ]
